version: '3'

services:
  database:
    image: postgres:11.15-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: ruby_app
      POSTGRES_DB: ruby_app_db
    ports:
      - 5432:5432


